# Generated by Django 2.2.4 on 2021-05-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='approvals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sct', models.CharField(max_length=15)),
                ('capitaux_propres', models.FloatField(default=0)),
                ('passifs_non_courant', models.FloatField(default=0)),
                ('total_bilan', models.FloatField(default=0)),
                ('stock', models.FloatField(default=0)),
                ('creance_client', models.FloatField(default=0)),
                ('actif_immobilier', models.FloatField(default=0)),
                ('resultat_net', models.FloatField(default=0)),
                ('chiffre_d_affaires', models.FloatField(default=0)),
            ],
        ),
    ]
